export const BODY_PADDING = 30
export const BODY_PADDING_PX = `${BODY_PADDING}px`

export const WIDTH_LEFT_COLUMN = 208
export const WIDTH_LEFT_COLUMN_PX = `${WIDTH_LEFT_COLUMN}px`

export const HEIGHT_HEADER = 45
export const HEIGHT_STATION_HEADER_IMAGE = 250
export const HEIGHT_STATION_HEADER_IMAGE_PX = `${HEIGHT_STATION_HEADER_IMAGE}px`

export const Z_INDEX_TWITTER_PREVIEW_UNDERLAY = 48
export const Z_INDEX_TWITTER_PREVIEW = 49
export const Z_INDEX_APP_LEFT_COLUMN = 50
export const Z_INDEX_STATION_HEADER = 50
export const Z_INDEX_APP_HEADER = 51
